### ISSUE TITLE
Windows image

### ISSUE THREAD

**Issue by iLLiac4** [Atlan4/Fnirsi1013D#1]
Hi.

Is it possible to create an sd image of it so windows users can flash it with Rufus?

TNX

**Comment by Atlan4** [comment]
No one is responsible for anything, you do everything at your own risk.

To upload the firmware under Windows, download the LOADER.zip file, unzip it and run it. Turn on the oscilloscope, connect the USB cable, select the option to turn on USB in the oscilloscope menu. After about 2 seconds to 1 minute, windows will recognize the device and open a window with folders. Now in the loader program, select the BIN you want to load. Upload it to the device, touch the screen to turn off the usb, and turn off the oscilloscope.

https://www.youtube.com/watch?v=LVI45oJHTK8

https://www.youtube.com/watch?v=OYxfj4rTF_E

In case of problems with the touch screen, see this: configuration_file.txt

Loader allows you to return the oscilloscope card to the previous firmware, the new firmware is stored only on the SD card, where the original is loaded in the flash of the device.
The safe solution is to use another SD card. Upload the firmware there, and insert the cards in the device.

Everything is described on the pages https://www.eevblog.com/forum/testgear/fnirsi-1013d-100mhz-tablet-oscilloscope/msg5172177/#msg5172177

Original source https://github.com/pecostm32/FNIRSI_1013D_Firmware

**Comment by iLLiac4** [comment]
TNX must have missed that tool. Will try it.
